name: historias_admin
description: Admin web para gerenciamento do Historias App
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  google_sign_in: ^6.2.1
  cached_network_image: ^3.3.1
  mask_text_input_formatter: ^2.9.0
  cupertino_icons: ^1.0.8
  
  # Núcleo Firebase
  firebase_core: ^3.8.0

  # Serviços Firebase (adicione só os que usar)
  firebase_auth: ^5.3.4
  cloud_firestore: ^5.6.0
  firebase_storage: ^12.3.0
  cloud_functions: ^5.2.0
  mask_text_input_formatter: ^2.9.0

  # Outras (opcional)
  firebase_analytics: ^11.3.0
  firebase_crashlytics: ^4.1.0

  # Utilitários/UI (remova se não usar)
  provider: ^6.1.2
  http: ^1.2.2
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/