// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCacDV-Y3tHd2sz2FfQhMy9mVmA9e4pUWU',
    appId: '1:826670569395:web:8bad2f04c92bf512a0ddc6',
    messagingSenderId: '826670569395',
    projectId: 'livro-historias',
    authDomain: 'livro-historias.firebaseapp.com',
    storageBucket: 'livro-historias.firebasestorage.app',
    measurementId: 'G-EFERRY20MG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAsi43GfF11yhD5xDSPrIaEN7xSnxY62hU',
    appId: '1:826670569395:android:836ff6408918eb4da0ddc6',
    messagingSenderId: '826670569395',
    projectId: 'livro-historias',
    storageBucket: 'livro-historias.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDo-hEro9lwPqr5ar2JUwtQlSq6CEY21cQ',
    appId: '1:826670569395:ios:0bca3df0b307c6e4a0ddc6',
    messagingSenderId: '826670569395',
    projectId: 'livro-historias',
    storageBucket: 'livro-historias.firebasestorage.app',
    iosClientId: '826670569395-p1nt8oml9semo391cpehhlb1ula4825n.apps.googleusercontent.com',
    iosBundleId: 'com.example.tmpFirestoreTest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDo-hEro9lwPqr5ar2JUwtQlSq6CEY21cQ',
    appId: '1:826670569395:ios:0bca3df0b307c6e4a0ddc6',
    messagingSenderId: '826670569395',
    projectId: 'livro-historias',
    storageBucket: 'livro-historias.firebasestorage.app',
    iosClientId: '826670569395-p1nt8oml9semo391cpehhlb1ula4825n.apps.googleusercontent.com',
    iosBundleId: 'com.example.tmpFirestoreTest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCacDV-Y3tHd2sz2FfQhMy9mVmA9e4pUWU',
    appId: '1:826670569395:web:e91c8d74edf012cba0ddc6',
    messagingSenderId: '826670569395',
    projectId: 'livro-historias',
    authDomain: 'livro-historias.firebaseapp.com',
    storageBucket: 'livro-historias.firebasestorage.app',
    measurementId: 'G-KCT79HJZGM',
  );
}
